### PR TITLE
Refactoring and bump version to 3.1.1

### PR DESCRIPTION
**Pull request by Krasnyanskiy**
1. Removed `final` access modifier from classes to improve code extensibility.
2. Bumped app version.

### CODE REVIEW

**Comment by aramrami** [comment]
Done.
When do you plan to publish the project in Maven Central?
Thanks.
Azzeddine

2015-09-02 23:21 GMT+02:00 Alexander Krasnyanskiy <notifications@github.com>
:

**Comment by Krasnyanskiy** [comment]
I'm not sure if it possible to do that without permissions of original author (Eric Sheridan). Do you communicate with Eric?

**Comment by aramrami** [comment]
I am now the project leader and I have all right to change, add, modify, to
add people, etc.

Eric has no thing to do with the project.

If you want to join the project you are welcome, if not use it as you want
and have nice time.

I will analyze deeply your pull request this week-end to see if I keep your
merge or not.

I accept it because your proposal was good.

I hope it is clear for you?

Azzeddine RAMRAMI
IBM Security IT Architect & IBM Inventor
OWASP CSRFGurad Project Leader
+33 6 65 48 90 04

**Comment by aramrami** [comment]
Remove final class is not secure.

But making a class final prevents a malicious subclass from adding finalizers, cloning, and overriding random methods (Secure Coding Guideline 4-5)

So I will keep the original code with final access.

**Comment by Krasnyanskiy** [comment]
@aramrami I'm talking about changing `final` modifier, and not 'bout class removing. 

> adding finalizers

Hmm... how many times did you meet code stuff like this?

> So I will keep the original code with final access

Of course you can keep the original code as is. It's up to you. But there are cases when developers need to extend existed class and change some logic. It's not the security issue, it's design needs (to avoid code duplication, etc). If you make class final then it would be impossible to extend it.

**Comment by aramrami** [comment]
I teach secure coding to a lot of student.
Do you mean that I have no knowledge in Java !!!  Your question is really
not professional.

I am now working on the version 4.0 with a new code design and new
techniques.
And I will keep the final modifier in the new version AS I WROTE.

I will close this discussion.
Thanks.
Azzeddine

2015-09-03 13:47 GMT+02:00 Alexander Krasnyanskiy <notifications@github.com>
:

**Pull request merged**
